### ISSUE TITLE
Program nie działa

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [orestwojtowicz/Epam_Magic_Numbers_Wojtowicz#1]
java.io.FileNotFoundException: resources/angular.png (Nie ma takiego pliku ani katalogu)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at com.wojtowicz.controller.read_hex_values.ReadHexFromFile.readHexValues(ReadHexFromFile.java:32)
	at com.wojtowicz.controller.CompareFileMagicNumbers.readHexValuesFromFile(CompareFileMagicNumbers.java:97)
	at com.wojtowicz.controller.CompareFileMagicNumbers.checkIfGivenFileExtensionIsCorrect(CompareFileMagicNumbers.java:37)
	at com.wojtowicz.Main.main(Main.java:44)
Exception in thread "main" java.lang.NullPointerException
	at com.wojtowicz.controller.CompareFileMagicNumbers.readHexValuesFromFile(CompareFileMagicNumbers.java:97)
	at com.wojtowicz.controller.CompareFileMagicNumbers.checkIfGivenFileExtensionIsCorrect(CompareFileMagicNumbers.java:37)
	at com.wojtowicz.Main.main(Main.java:44)

**Comment by orestwojtowicz** [comment]
Popełniłem błąd i nie sprawdziłem, czy program pobrany z repozytorium będzie działał prawidłowo. Dodałem mavena, więc problem z nie wczytywaniem plików powinien być rozwiązany.

**Comment by LIttleAncientForestKami** [comment]
[tammo@lafk-T470 kolejneMagiczneNumerki]$ ls                                                                                                                                                                                        [INSERT]
out  pom.xml  src
[tammo@lafk-T470 kolejneMagiczneNumerki]$ mvnp                                                                                                                                                                                      [INSERT]
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.wojtowicz:Epam_Magic_Numbers_Wojtowicz >-------------
[INFO] Building Epam_Magic_Numbers_Wojtowicz 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ Epam_Magic_Numbers_Wojtowicz ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ Epam_Magic_Numbers_Wojtowicz ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 7 source files to /home/tammo/tmp/magNum/kolejneMagiczneNumerki/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Epam_Magic_Numbers_Wojtowicz ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory /home/tammo/tmp/magNum/kolejneMagiczneNumerki/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ Epam_Magic_Numbers_Wojtowicz ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ Epam_Magic_Numbers_Wojtowicz ---
[INFO] No tests to run.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ Epam_Magic_Numbers_Wojtowicz ---
[INFO] Building jar: /home/tammo/tmp/magNum/kolejneMagiczneNumerki/target/Epam_Magic_Numbers_Wojtowicz-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.091 s
[INFO] Finished at: 2020-01-27T15:27:56+01:00
[INFO] ------------------------------------------------------------------------
[tammo@lafk-T470 kolejneMagiczneNumerki]$ java -jar target/Epam_Magic_Numbers_Wojtowicz-1.0.jar                                                                                                                                     [INSERT]
no main manifest attribute, in target/Epam_Magic_Numbers_Wojtowicz-1.0.jar

odpalanie jak rozumiem działa tylko z IDE?

**Comment by LIttleAncientForestKami** [comment]
Apka zakodowana na sztywno - działa tylko dla konkretnego PDFa.

**Comment by LIttleAncientForestKami** [comment]
W specce na pewno jest, że czytamy każdy plik (podejmujemy próbę). Tutaj wymaga to ingerencji w kod przed odpaleniem.

**Comment by orestwojtowicz** [comment]
No tak, ma Pan racje. Zamiast podawać jaki format może mieć plik, powinna być metoda, która porówna daną wartość hex z zawartością całością zawartości enumów. Będę wiedział, na co bardziej uwagę skupić. Dziękuję za opinie.
